name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
     
    steps: 
        #checckout the repository
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Build Project
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghrc.io/${{ vars.REPOSITORY }}:latest
            ghrc.io/${{ vars.REPOSITORY }}:${{ github.run_number }}
